var name1 = 'Muhammad Ahmad Raza';
console.log(name1);
var name2 = 'Raza';
console.log(name2);
var age = '18';
console.log(age);
var address = 'Block NO136 House No6 Majeed SRE';
console.log(address);
var education = 'Inter';
console.log(education);
var height = '5.11';
console.log(height);
